// Generated by LiveScript 1.3.1
(function(){
  var gulp, gulpLivescript;
  gulp = require('gulp');
  gulpLivescript = require('gulp-livescript');
  gulp.task('build', function(){
    return gulp.src('./src/*.ls').pipe(gulpLivescript({
      bare: true
    })).on('error', function(it){
      throw it;
    }).pipe(gulp.dest('./lib/'));
  });
  gulp.task('default', function(){
    gulp.run('build');
    return gulp.watch(['./src/*.ls', './src/**/*.ls'], function(){
      return gulp.run('build');
    });
  });
}).call(this);
