// Generated by LiveScript 1.3.1
(function(){
  module.exports = {
    log: function(str){
      return console.log(str);
    },
    error: function(str){
      return console.error(str);
    }
  };
}).call(this);
