// Generated by LiveScript 1.3.1
(function(){
  var logger, utils;
  logger = require('./logger');
  utils = require('./utils');
  exports.Request = {
    getCookie: function(key, dft){
      return this.cookies[key] || dft;
    },
    getSecureCookie: function(key, dft){
      var value, parts, len, expires, signature, localSig;
      value = this.cookies[key];
      if (!value) {
        return dft;
      }
      parts = value.replace(/\*/g, '=').split('|');
      if (parts.length !== 4) {
        return dft;
      }
      len = parts[0], value = parts[1], expires = parts[2], signature = parts[3];
      value = utils.base64.decode(value).substr(0, len);
      if (+expires < Date.now()) {
        return dft;
      }
      localSig = utils.hexHmacSha1(parts.slice(0, 3).join('|'), this.config.cookieSecureToken);
      if (localSig !== signature) {
        logger.error('invalid cookie signature: ' + key);
        return dft;
      }
      return value;
    }
  };
}).call(this);
