// Generated by LiveScript 1.3.1
(function(){
  var Ove, app;
  Ove = require('../..');
  app = new Ove;
  app.get('/test/', function(){
    return this.send('hello world');
  });
  app.post('/foo/:name/bar/:age/', function(){
    console.log(this.params);
    return this.json(this.form);
  });
  app.listen();
}).call(this);
