// Generated by LiveScript 1.3.1
(function(){
  var ove, app;
  ove = require('../..');
  app = ove();
  app['static']('/public/', './public').use(function(next){
    console.log('md0', this.url);
    return next();
  }).use(function(next){
    console.log('md1', this.url);
    return next();
  }).registerStatus(404, function(){
    return this.send('ooooooooooooooh, noooooooooooooo!');
  }).register('/test/', function(){
    this.setCookie('love', 'you');
    console.log('cookies:', this.cookies, '\n');
    console.log('headers:', this.headers, '\n');
    console.log('ip:', this.ip, '\n');
    this.setSecureCookie('miss', this.queryParams.miss || 'home');
    return this.send('hello world');
  }).get('/user/:uid/', function(){
    var cookie;
    cookie = this.getSecureCookie('miss', 'nothing');
    return this.send('hello ' + this.params.uid + ', miss ' + cookie);
  }).get('/redirect/', function(){
    return this.redirect('/user/yetone/');
  }).post('/foo/:name/bar/:age/', function(){
    console.log(this.body);
    console.log(this.params);
    return this.json(this.form);
  }).run();
}).call(this);
